### ISSUE TITLE
Plugins all got deactivated after adding folder into plugin folder

### ISSUE THREAD

**Issue by GeminiKiller** [nawawi/docket-cache#11]
Hi I have a problem when i add new plugin in plugin folder, all my plugin suddenly deactivated.  I tried to replace my active plugin data in wp_options database, it doesn't activated until i flush the cache. Could you help fix this issue?

**Comment by nawawi** [comment]
Hi,

I can't replicate the issue, everything seems to work as it should. You can try to disable the object cache "Docket Cache -> Overview -> Disable Object Cache" or deactivate the docket cache before adding a new plugin in the plugin folder.

You can't manually update the wp_options table in the database, if the persistent object cache plugins are active, like docket cache, since the cache will not be updated.

Thanks.

**Comment by nawawi** [comment]
**Update:**

You can try the dev version here  http://docketcache.com/devtest/docket-cache-dev2114.zip , hope it can solve the issue.

Thanks.
