### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by WEBzaytsev** [nawawi/docket-cache#12]
Hello!
When using the plugin on a large site (WooCommerce + dokan + WPML + theme + wp rocket + other plugins ) 
I get a 503 error on the second language part of the site (We have en and de). The error is not immediate, I detect it as follows: I want to go to the English version of the site almost all the pages, then I go to the German version and start walking through products and pagination, and if there is no error I walk through all the pages
I can provide our test dev server, and help in any way possible

**Comment by nawawi** [comment]
Hi,

503 error issue normally caused by memory burst, error on code, or when php reached the certain limit at runtime configuration. To identify which part of the issue, we need to enable WP_DEBUG. If you have not done it yet, please add this code at wp-config.php file:

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

try again the step that cause the error and monitor the logfile located at you site path /wp-content/debug.log

or you can enable WP_DEBUG at Docket Cache runtime configuration:

Configuration -> Runtime Options -> WP Debug
Configuration -> Runtime Options -> WP Debug Log

![Screenshot-20210910124321-887x587](https://user-images.githubusercontent.com/1203635/132800897-6bd71913-4cb4-43bd-abe1-c7156ad17297.png)


For quick solutions, you can try:
1. Disable wp rocket cache preloading option.
2. Disable docket cache Advanced Post Caching.
3. Disable docket cache Object Cache Precaching.
4. Disable docket cache Admin Object Cache Preloading.


![Screenshot-20210910124143-819x283](https://user-images.githubusercontent.com/1203635/132800827-bea1a1ab-76c5-4f7e-ae33-e5190be25dfc.png)

Thanks.
